project:
  type: website
  output-dir: public

website:
  title: "Yogi Jenny"
  
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - practice.qmd

  

format:
  html:
    theme: Quartz
    css: styles.css
    toc: true
